### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ghost** [joshglendenning/win10-desktop-switcher#5] opened 2023-02-26 03:29 UTC
I was delighted to find this and use it on my main desktop about eleventy-dozen times a day. But I see MS broke it with Win11. Before I try to see if I can grok the code and do it myself, are you already on that?

**Comment by isobit** [comment] 2023-02-26 15:40
I'm delighted to hear this has gotten so much use! Unfortunately I haven't used Windows as a daily driver for some time so I haven't been motivated to add support for Windows 11. I do see there is [another issue](https://github.com/isobit/win10-desktop-switcher/issues/3) regarding Windows 11 so I'll close this as duplicate of that and continue the conversation over there.

**Closed as not planned by isobit** 2023-02-26 15:40 UTC

**Comment by ghost** [comment] 2023-02-26 15:51
I’m a reluctant Windows guy myself, but if I’m going to use it I’m going to want it to work well. So I’ll probably dive into the code and see if I can figure it out. Count yourself lucky you got out before Win11, about the most annoying ‘upgrade’ I can remember in a good while.

FWIW, I found a way to do it in PowerShell but it’s slow. Even compiling the .ps1 down an .exe is slow compared to your method, but that’s what I’m doing for now.
